[package]
name = "strand"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = { version = "0.11", features = ["libadwaita"] }
gtk = { package = "gtk4", version = "0.11" }
adw = { package = "libadwaita", version = "0.9" }
sourceview5 = "0.11"
unicode-segmentation = "1.12"
unicode-width = "0.2"
unicode-general-category = "1.1"
bitflags = "2.9"
ctor = "0.2"
